## Server configuration
#server.port=8080
#
## Database configuration
#spring.datasource.url=jdbc:mariadb://localhost:3311/filetranslator
#spring.datasource.username=root
#spring.datasource.password=heslo
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#
## Mail configuration
#spring.mail.host=localhost
#spring.mail.port=1025
#
## oAuth2 configuration for Google - JENOM V RAMCI SEMESTRALKY, JINAK SEM NE!!! - DULEZITE!!!  - pridavame v docker-compose.yml
##spring.security.oauth2.client.registration.google.client-id=
##spring.security.oauth2.client.registration.google.client-secret=
##spring.security.oauth2.client.registration.google.scope=profile,email
#
#
## JPA/Hibernate configuration
#spring.jpa.hibernate.ddl-auto=validate
#
## Enable SQL query logging
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
#
## File upload configuration
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#
## Logging configuration
#logging.level.root=INFO
#logging.level.cz.zcu.vodickad=DEBUG
#logging.level.org.springframework.security=DEBUG
#
## Thymeleaf configuration
#spring.thymeleaf.cache=false
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#
## Security logging
#logging.level.org.springframework.web=DEBUG
#
#server.servlet.encoding.charset=UTF-8
#server.servlet.encoding.force=true


#todo nastavit neco takoveho