## Persistence layer specific configuration
## JPA specific settings
#
#
## Disable Open Session in View pattern
#spring.jpa.open-in-view=false
#
## "Pokud m\u00E1? prov\u00E9st v\u00EDce stejn\u00FDch operac\u00ED (nap?. 200 INSERT?), nepos\u00EDlejje do
## datab\u00E1ze po jednom. M\u00EDsto toho je seskup do bal\u00EDk? po 20 a po?li je najednou."
#spring.jpa.properties.hibernate.jdbc.batch_size=20
#
## Optimize batch inserts and updates
#spring.jpa.properties.hibernate.order_inserts=true
#spring.jpa.properties.hibernate.order_updates=true
#
## Enable batching for versioned data
##spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
#
## Connection pool settings
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.connection-timeout=20000
#
#spring.sql.init.mode=always


#todo nastavit pro docker a pro testovani